packages:
  - 'packages/*'
  - 'local-first-chat/*'
  - 'browser-extension/*'
  - 'tooling/*'

catalog:
  "@ianvs/prettier-plugin-sort-imports": ^4.4.0
  eslint: ^9.17.0
  prettier: ^3.4.2
  typescript: ^5.7.3
  react: ^19.0.0
  react-dom: ^19.0.0
  tsup: ^8.3.5
  '@types/node': "^22.10.3"
  "@types/dom-chromium-ai": "^0.0.4"
  "tslib": "^2.8.1"
  "hono": "^4.6.17"
  zod: ^3.24.1
  "drizzle-orm": "^0.38.4"
  "babel-plugin-react-compiler": "^19.0.0-beta-27714ef-20250124"
  "@types/react": "^19.0.3"
  "@types/react-dom": "^19.0.3"



