packages:
  - 'packages/!(chrome-ai)'
  - 'local-first-chat/*'
  # - 'browser-extension/*'
  - 'tooling/*'

catalog:
  "@ianvs/prettier-plugin-sort-imports": ^4.4.0
  eslint: ^9.17.0
  prettier: ^3.4.2
  typescript: ^5.7.2
  tsup: ^8.3.5
  '@types/node': "^22.10.3"
  "@types/dom-chromium-ai": "^0.0.4"
  "tslib": "^2.8.1"
  "hono": "^4.6.17"
  "drizzle-orm": "^0.38.4"


