# fly.toml app configuration file generated for local-first-chat-electric on 2024-12-28T15:09:02-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'local-first-chat-electric'
primary_region = 'ord'

[build]
  image = 'electricsql/electric:latest'

[env]
  DATABASE_URL = 'postgres://postgres:mFzA27MXRaQcSQnS@db.tckgqruzlylrgghctont.supabase.co:5432/postgres?sslmode=require'
  ELECTRIC_DATABASE_USE_IPV6 = 'true'

[http_service]
  internal_port = 3000
  force_https = true

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '20s'
    method = 'GET'
    path = '/v1/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
